language: ruby

rvm:
  - "2.2.0"

services:
  - mongodb

sudo: false

deploy:
  provider: heroku
  api_key:
    secure: "D8yLQzpsEyYnwsiAda9+29SaORNHzV49FIvHtL0nobRUG/ChYieH17OV6feFFBViJoAbKTg0nVl+2jA57QDazBxdFV38VG30V6/kPeLqYAbh4eHTdgiv/ucaz+7U2KN/ybeQaNtw1YE3T/8DcqsG3ExFC5v9bDI6uok9QN1KSuc="
  app:
    master: ssnip

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES="YES"
    - DISPLAY=":99.0"
    - RACK_ENV="test"

